method: grid
program: src/main.py

# Without specifying this command explicitly, all arguments will be passed on the command line.
command:
  - ${env}
  - ${interpreter}
  - ${program}

parameters:
  data_config:
    values: ['data_config/SchoolPerformanceUnbiased.yaml', 'data_config/ACSEmployment.yaml', 'data_config/ACSIncome.yaml', 'data_config/ACSMobility.yaml', 'data_config/ACSPublicCoverage.yaml', 'data_config/ACSTravelTime.yaml', 'data_config/SchoolPerformanceBiased.yaml']

  data:
    parameters:
      main_sens_format:
        values: ["binary", "intersectional"]

  method:
    parameters:
      name:
        value: error_parity
      fairness_strength:
        values: [0.005, 0.01, 0.05, 0.1, 0.2]
      statistic:
        values: ['pr', 'tpr', 'fpr','eo']

  seed:
    values: [0, 1, 2, 3, 4]
