method: grid
program: src/main.py

# Without specifying this command explicitly, all arguments will be passed on the command line.
command:
  - ${env}
  - ${interpreter}
  - ${program}

parameters:
  data:
    parameters:
      main_sens_format:
        value: binary
  
  data_config:
    values: ['data_config/SchoolPerformanceUnbiased.yaml', 'data_config/ACSEmployment.yaml', 'data_config/ACSMobility.yaml', 'data_config/ACSPublicCoverage.yaml', 'data_config/ACSTravelTime.yaml', 'data_config/SchoolPerformanceBiased.yaml']

  method:
    parameters:
      name:
        value: disparate_impact
      fairness_strength:
        values: [0.1, 0.3, 0.5, 0.8, 1]

  data: 
  seed:
    values: [0, 1, 2, 3, 4]
