data_config: data_config/SchoolPerformanceBiased.yaml
method:
  name: "laftr"
  fairness_strength: 1
  adv_dim: [16]
  reconstruction_strength: 1
  label_given: False
data: 
  main_sens_format: binary
seed: 0